create table if not exists public.club_events (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.clubs(id) on delete cascade,
  created_by_user_id bigint not null references public.users(id) on delete cascade,
  type varchar(24) not null default 'event' check (type in ('training', 'match', 'meeting', 'event')),
  title varchar(180) not null,
  description text,
  location varchar(255),
  starts_at timestamptz not null,
  ends_at timestamptz,
  all_day boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_club_events_club_starts_at
  on public.club_events(club_id, starts_at);

create index if not exists idx_club_events_creator
  on public.club_events(created_by_user_id);
