begin;

-- Full reset of legacy app tables (public schema)
drop table if exists public.chat_messages cascade;
drop table if exists public.team_invitations cascade;
drop table if exists public.two_factor_codes cascade;
drop table if exists public.password_resets cascade;
drop table if exists public.pending_registrations cascade;
drop table if exists public.sms_verifications cascade;
drop table if exists public.clubs cascade;
drop table if exists public.users cascade;
drop type if exists public.user_role;

create type public.user_role as enum ('hráč', 'trenér', 'manažer', 'rodič', 'jiné');

create table public.users (
  id bigint generated by default as identity primary key,
  first_name varchar(100) not null,
  last_name varchar(100) not null,
  email varchar(255) not null unique,
  phone varchar(30),
  profile_picture varchar(255),
  role public.user_role default 'hráč',
  organization varchar(255),
  password_hash varchar(255) not null,
  two_factor_enabled boolean default false,
  created_at timestamptz not null default now(),
  admin boolean default false
);

create table public.clubs (
  id bigint generated by default as identity primary key,
  owner_user_id bigint not null references public.users(id) on delete cascade on update cascade,
  name varchar(255) not null,
  sport varchar(120) not null,
  city varchar(120) not null,
  logo varchar(255),
  address varchar(255) not null,
  ico varchar(20) not null,
  dic varchar(30) not null,
  website varchar(255) not null,
  club_email varchar(255) not null,
  club_phone varchar(40) not null,
  primary_color varchar(7) not null default '#E43432',
  secondary_color varchar(7) not null default '#000000',
  accent_color varchar(7) not null default '#FFFFFF',
  created_at timestamptz not null default now()
);

create table public.chat_messages (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.clubs(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  message text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.password_resets (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token varchar(64) not null unique,
  used boolean default false,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table public.pending_registrations (
  id bigint generated by default as identity primary key,
  verification_token varchar(64) not null unique,
  club_name varchar(255) not null,
  sport varchar(100) not null,
  city varchar(100) not null,
  address varchar(255) not null,
  ico varchar(20) not null,
  dic varchar(20) not null,
  website varchar(255) not null,
  club_email varchar(255) not null,
  club_phone varchar(50) not null,
  first_name varchar(100) not null,
  last_name varchar(100) not null,
  email varchar(255) not null,
  phone varchar(50),
  password_hash varchar(255) not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create table public.sms_verifications (
  id bigint generated by default as identity primary key,
  phone varchar(32) not null,
  code varchar(10) not null,
  attempts integer default 0,
  expires_at timestamptz not null,
  created_at timestamptz not null
);

create table public.team_invitations (
  id bigint generated by default as identity primary key,
  token varchar(64) not null unique,
  club_id bigint not null references public.clubs(id) on delete cascade,
  inviter_user_id bigint not null references public.users(id) on delete cascade,
  email varchar(255) not null,
  role varchar(16) not null check (role in ('hráč', 'trenér', 'rodič')),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  used boolean default false
);

create table public.two_factor_codes (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  code varchar(255) not null,
  expires_at timestamptz not null,
  used boolean default false,
  created_at timestamptz not null default now()
);

create index idx_chat_messages_club on public.chat_messages(club_id);
create index idx_chat_messages_user on public.chat_messages(user_id);
create index idx_chat_messages_created on public.chat_messages(created_at);

create index idx_clubs_owner_user_id on public.clubs(owner_user_id);

create index idx_password_resets_token on public.password_resets(token);
create index idx_password_resets_user_id on public.password_resets(user_id);
create index idx_password_resets_expires_at on public.password_resets(expires_at);

create index idx_pending_registrations_token on public.pending_registrations(verification_token);
create index idx_pending_registrations_email on public.pending_registrations(email);
create index idx_pending_registrations_expires on public.pending_registrations(expires_at);

create index idx_sms_verifications_phone on public.sms_verifications(phone);
create index idx_sms_verifications_expires_at on public.sms_verifications(expires_at);

create index idx_team_invitations_token on public.team_invitations(token);
create index idx_team_invitations_email on public.team_invitations(email);
create index idx_team_invitations_club on public.team_invitations(club_id);
create index idx_team_invitations_inviter on public.team_invitations(inviter_user_id);

create index idx_two_factor_codes_user_id on public.two_factor_codes(user_id);
create index idx_two_factor_codes_code on public.two_factor_codes(code);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_chat_messages_updated_at
before update on public.chat_messages
for each row
execute function public.set_updated_at();

insert into public.users (id, first_name, last_name, email, phone, profile_picture, role, organization, password_hash, two_factor_enabled, created_at, admin) values
(19, 'Tomas', 'Kotik', 'tomaskotik08@gmail.com', '7322334723', 'user_19_1770662673.jpeg', 'manažer', 'RC Zlín', '$2y$12$P/h3UfvddH/GIlYrHnMsLeD8QngggcXvCQZNTwh1Txi5n3a/MHuIG', false, '2026-01-29 09:19:31+00', true),
(25, 'Martin', 'Kotík', 'mkotik@seznam.cz', '+420602468097', 'user_25_1769709796.jpg', 'hráč', 'RC Zlín', '$2y$12$wjX18QlW7C5XJhA5yQCTTOaLCHA/n3oMXsx7KBReg9JVD.KXGs7xm', false, '2026-01-29 17:58:50+00', false),
(26, 'Liliana', 'Krajčová', 'liliana.krajcova@seznam.cz', '604442366', 'user_26_1769711944.jpeg', 'hráč', 'RC Zlín', '$2y$12$i37n.YTNkkCzcxt6ddnqhu6I6gJ38fY6ThoazlTUJqey1XP1m68Ru', true, '2026-01-29 18:38:21+00', false),
(28, 'Tomáš', 'Žabčík', 'zabcik.tomas@seznam.cz', '774851747', null, 'hráč', 'RC Zlín', '$2y$12$a/9vFLGDdcqwfhh6S/7FuOF/bwy96iXnKclgUKfgxQWv5QII8VHdm', false, '2026-01-30 13:27:15+00', false),
(31, 'Tomáš', 'Pekáček', 'tomaskotik013@gmail.com', '+420 123 456 789', null, 'hráč', 'RC Zlín', '$2y$12$iJ1DLsOMI3bXUH4GEzBdqe.g/hOV07ANp1qVEpDH.W.FFBaQj9/sK', false, '2026-01-31 15:30:16+00', false),
(33, 'Marek', 'Sukup', 'marek.sukup@gmail.com', '123456', 'user_33_1769937115.jpg', 'hráč', 'RC Zlín', '$2y$12$z97LXduuIWxsQx6y3ViJKOyqDLiV4TwyQA9l8nLyDROt2/fGe/fYO', false, '2026-02-01 09:09:41+00', false),
(35, 'Dagmar', 'Gwuzdz', 'dajke@seznam.cz', '+420602546579', null, 'hráč', 'RC Zlín', '$2y$12$YNqT2RKtZ/pc.emIALuWIOf69cPcT4ZyqxLYj1R6zx4tIN.0ZeDbS', false, '2026-02-03 17:38:06+00', false),
(36, 'Matěj', 'Kadlčák', 'kadlcmatej01@gmail.com', '731 077 981', 'user_36_1770280780.jpg', 'hráč', 'RC Zlín', '$2y$12$3RpaLZ24bTmbj7eFYwpErOpxlSwkQU/syzQDBdOSt3TqWDuTk/ihu', false, '2026-02-05 08:25:52+00', false),
(38, 'David', 'Polaštík', 'david.polastik.dev@gmail.com', '', null, 'hráč', 'RC Zlín', '$2y$12$KKrZHKjIKdfiOZbuu2zax.KRwtjco91SjI3CTF0eXej4QNjPnVpdG', true, '2026-02-05 18:47:04+00', false),
(39, 'Martin', 'Máčalík', 'martin@avonet.cz', '+420777465800', null, 'hráč', 'RC Zlín', '$2y$12$p.zV4W2Yma9ZkrtjyWd/dOrV3zoSxNFafifR4dRaXXqAwB06mqsTa', false, '2026-02-13 15:01:48+00', false),
(40, 'Pluhacek', 'Jakub', 'pluhacekjakub99@gmail.com', '+1 2489 4893 84', null, 'hráč', 'RC Zlín', '$2y$12$jXZTTf0.0sUpJeRkE8qAmOWWzlkunfuuYE5kCahV0cu7NVRl3EOw.', false, '2026-02-16 11:00:55+00', false),
(41, 'Judita', 'Suchánková', 'juditasuchankova@seznam.cz', '+420776589657', 'user_41_1771429682.jpg', 'hráč', 'RC Zlín', '$2y$12$2g9WWmlt80M7xB9mZLKOKerk8e7pXC27WQ7PqBYK5km1cj5b8dx2i', true, '2026-02-18 15:46:26+00', false);

insert into public.clubs (id, owner_user_id, name, sport, city, logo, address, ico, dic, website, club_email, club_phone, created_at) values
(4, 19, 'RC Zlín', 'Ragby', 'Zlín', 'club_4_1770472472.png', 'Podvesná XIV', '1234567882', 'CZ612941', 'https://https/rczlin.cz', 'rctlin@gmail.com', '+420 897 213 123', '2026-01-29 09:19:31+00');

insert into public.sms_verifications (id, phone, code, attempts, expires_at, created_at) values
(1, '+420778494266', '432643', 0, '2026-02-12 19:01:05+00', '2026-02-12 18:51:05+00'),
(2, '+420778494266', '949157', 0, '2026-02-12 19:02:57+00', '2026-02-12 18:52:57+00'),
(3, '+420602546579', '782681', 0, '2026-02-12 19:05:42+00', '2026-02-12 18:55:42+00'),
(4, '602546579', '359409', 0, '2026-02-12 19:07:38+00', '2026-02-12 18:57:38+00'),
(5, '+420602546579', '005308', 0, '2026-02-12 19:08:16+00', '2026-02-12 18:58:16+00');

select setval(pg_get_serial_sequence('public.users', 'id'), coalesce((select max(id) from public.users), 1), true);
select setval(pg_get_serial_sequence('public.clubs', 'id'), coalesce((select max(id) from public.clubs), 1), true);
select setval(pg_get_serial_sequence('public.chat_messages', 'id'), coalesce((select max(id) from public.chat_messages), 1), true);
select setval(pg_get_serial_sequence('public.password_resets', 'id'), coalesce((select max(id) from public.password_resets), 1), true);
select setval(pg_get_serial_sequence('public.pending_registrations', 'id'), coalesce((select max(id) from public.pending_registrations), 1), true);
select setval(pg_get_serial_sequence('public.sms_verifications', 'id'), coalesce((select max(id) from public.sms_verifications), 1), true);
select setval(pg_get_serial_sequence('public.team_invitations', 'id'), coalesce((select max(id) from public.team_invitations), 1), true);
select setval(pg_get_serial_sequence('public.two_factor_codes', 'id'), coalesce((select max(id) from public.two_factor_codes), 1), true);

commit;
