begin;

create table if not exists public.device_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token_selector varchar(64) not null unique,
  token_hash varchar(128) not null,
  user_agent varchar(255),
  ip_address varchar(64),
  expires_at timestamptz not null,
  revoked boolean not null default false,
  last_used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_device_tokens_user_id on public.device_tokens(user_id);
create index if not exists idx_device_tokens_expires_at on public.device_tokens(expires_at);
create index if not exists idx_device_tokens_revoked on public.device_tokens(revoked);

commit;
