begin;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  club_id bigint references public.clubs(id) on delete cascade,
  type varchar(64) not null,
  -- 'new_message' | 'member_joined' | 'invite_accepted'
  title varchar(255) not null,
  body text,
  actor_id bigint references public.users(id) on delete set null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_notifications_user_id on public.notifications(user_id);
create index if not exists idx_notifications_user_read on public.notifications(user_id, read_at);
create index if not exists idx_notifications_created on public.notifications(created_at desc);

-- Enable Supabase Realtime for this table
alter publication supabase_realtime add table public.notifications;

commit;
